name: Debricked scan

on: [push, pull_request]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Conan SBOM generator # https://github.com/CycloneDX/cyclonedx-conan
      run: |
          python -m pip install cyclonedx-conan 
          python -m pip install markupsafe==2.0.1
          python -m pip install -U conan
    - name: Generate Conan SBOM
      run: |
          cyclonedx-conan conanfile.txt | sed -n -e '/^{/,$p' > sbom.json # cyclonedx-conan PATH_TO_conanfile.txt > SBOM_NAME_FILE
          ls
    - uses: debricked/actions@v4
      env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
